---
- name: download yarn
  get_url:
    url: "https://yarnpkg.com/install.sh"
    dest: /tmp/install-yarn.sh

- name: install yarn
  shell: "cat /tmp/install-yarn.sh | bash -s -- --version 1.12.3"
  args:
    creates: /usr/local/bin/yarn
...